### ISSUE TITLE
Day #016 - Mon Aug 28 12:04 AM - 10

### ISSUE THREAD

**Issue by gracepal** [gracepal/code-muscle#16]
# Today

What gets measured gets managed. -Peter Drucker

Total 17 🪴, 6 🌱 - 10h

<img width="26" alt="knight" src="https://github.com/gracepal/code-muscle/assets/131278381/28cf2c6a-1813-4f5c-ac1b-5901397a5097"> pomodoro 2hr 👩‍🎓 1hr ☕  30m 🪴 15m 🌱
----
#### 💠 Scripts
- [X] Yesterday's script - reset study plan does not persist cleared state outside driver 🌱 
#### 💠 Task Based
- [X] 100 Days of Code - Day 16, OOP 🪴🪴🪴🪴 
- [X] Chrome extensions - data fetching 🪴🪴🪴🪴 🌱 
- [X] Python Networking - continue terminal chat room with threading 🪴 🌱 
- [X] Bek Python OOP - classes intro 🪴 
#### 💠 Round robin
- [x] Today's Daily Problem  [🟢 225. Implement Stack using Queues](https://leetcode.com/problems/implement-stack-using-queues/) 🪴 
- [X] Backlog Daily Problems August 🪴🪴🪴
- [X] Online Assessment 🪴🪴 
- [X] The Blind 75 🌱 (1,2)
#### 💠 Time Pass
- [X] Khan math `gr4/a2/u1L1` 🌱 
- [X] Coursera Algo 1 - mid-assignment, printing args 🪴 🌱 
- [X] Jonas JS intro sections 🌱 

# Confidence is earned.
