### ISSUE TITLE
Day #028 - Sat Sep 9 4:42 AM - 7.5

### ISSUE THREAD

**Issue by gracepal** [gracepal/code-muscle#29]
# Today

What gets measured gets managed. -Peter Drucker
![linkedin-logo-png-2032](https://github.com/gracepal/code-muscle/assets/131278381/0f136418-3744-4423-88bf-9348c9f65b11)

## Stretch, 🌳 90m
- Notes App 
  - [ ] threading review 🪴🪴
  - [ ] condition wait(), notify(), notify_all()

## Core, 🪴 30m
- [x] Angela Yu #100daysofcode - Day 25 🪴🪴
- [X] Angela Yu #100daysofcode - Day 26 🪴🪴
- [X] Angela Yu #100daysofcode - Day 27 🪴🪴🪴🪴🪴
- [X] Angela Yu #100daysofcode - Day 28 🪴🪴🪴🪴
- [ ] Daily Problem 
- [ ] Colt Steele Pandas

## Timboxed
- [ ] Khan Math
- [ ] Xian - chrome extensions
- [ ] Art of Doing - python projects
- [ ] Colt - css grid
